name: CI/CD for Ecommerce App

on:
  push:
    branches: ["main"]

jobs:
  Terraform-infra:
    name: Terraform Infra
    runs-on: ubuntu-latest
    steps:
      - name: display terraform
        run: |
      echo "Terraform infra"